# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b4fa548c9924582f764ed1be493dbb2f0768a227a7977ca9715d64e797b7378bdf5df20f6c18006d55aaab2813ddc459da2a85cbd63cac4cdd8b79e049e63a3

test:
  secret_key_base: 2c8d6a3d205d6b111152a0775207b16cb50a40af99858d227e299a0bae8b6788bb620dcb6242f52cd5ac0094fb99a8f163f4eeb034bebe77e8659c3c5ef7f5cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
